name: Load South Carolina Jurisdictions

on:
  workflow_dispatch:   # lets you trigger manually from GitHub UI
  schedule:
    - cron: "0 3 * * 0"   # runs every Sunday at 3 AM UTC

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install node-fetch@2 @supabase/supabase-js

      - name: Run ETL script
        run: node etl/load_sc.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
